### PR TITLE
Witty pi energy manager software

### PR DESCRIPTION
**Pull request by imvectech**
###  WHAT

Witty pi mini is a Uugear RPi shield capable of managing energy of the RPi together with keeping time using an embedded RTC.

https://github.com/uugear/Witty-Pi-2

We are working on a timelapse camera for river monitoring. The intention is to turn on the rpi 5 minutes every hour and take a picture. Simple as that. The Witty pi controls the On/OFF of the RPi sending zero voltage to the Pi to fully turn it off. After 55 minutes the Witty sends a electrical signal and the Pi boots up.

We've already done this using raspbian and want to use the PL camera kit instead ;D

In the recipe we also include a pythin script for the timelapse and some packages needed.

### Download instructions

Generating the image will take a few minutes. Once the image is prepared, and if it succeeded, you'll see a green checkmark at the bottom of the pull request. To download the image:

1. click the green checkmark; you'll go to a page at a URL like `https://gitlab.com/publiclab/image-builder-rpi/pipelines/########/builds`
2. On this page, click the `Jobs` tab, next to `Pipeline`
3. Click the green `Passed` button
4. Click `Download` in the right-hand sidebar
5. Unzip the `artifacts.zip` file, and also the `hypriotos-rpi-camera_web.img.zip` within it
6. Use a program like https://etcher.io/ to flash it to an SD card

You'll also be able to read the output of the image generation in this window.

We hope to create a bot to report back the completed image URL in each pull request. If you can help create such a bot, please contact us at:

https://github.com/publiclab/image-builder-rpi/issues/16

Thanks!

### CODE REVIEW

**Comment by imvectech** [comment]
Witty pi mini is a Uugear pcb capable of managing energy of the RPi togheter with keeping time with an embedded RTC.

**Comment by jywarren** [comment]
Hmm, @icarito is it just taking a while for the GitLab process to begin? 

Exciting!!! :-)

I wonder if this would make the Pi last a lot longer using one of these little batteries :-) https://www.amazon.com/s/?ie=UTF8&keywords=cr123a 🔋 ⚡️ 😴

**Comment by imvectech** [comment]
Is it possible that importing those files to github simplifies the hole thing?

**Comment by imvectech** [comment]
Sorry didn't intend to merge branch witty into patch-1 but the opposite ;D

**Comment by icarito** [comment]
I'm guessing PR into `master` are built automatically by GitLab?
e.g. https://gitlab.com/publiclab/pi-builder/-/jobs/115498371

**Comment by jywarren** [comment]
Ah ok, so @imvectech you just have to open the PR against the master branch instead of the witty branch! Or I could merge it and reopen the witty pr?

**Comment by imvectech** [comment]
ok closing here and opening a new one. This is being a 100%git learning process. I'll try to install the Witty pi and try our approach with the timelapse already provided ;)

**Pull request closed without merging**
