### PR TITLE
Install infragram

### PR DESCRIPTION
**Pull request by jywarren**
Thanks for opening a pull request! In this repository, opening a PR will initiate the generation of a new Raspberry Pi image, and create an image file you can download and use in your Raspberry Pi.

The changes you add to the pull request, such as adding software to install, will be run on the generated image.

For an example, see the software installed and configured in this pull request: https://github.com/publiclab/image-builder-rpi/pull/15/files

### Recipe

Use this space to describe what your "recipe" is intended to install and configure on a Raspberry Pi:

Installing Infragram multispectral analysis tool: https://github.com/publiclab/infragram

****

### Download instructions

Generating the image will take a few minutes. Once the image is prepared, and if it succeeded, you'll see a green checkmark at the bottom of the pull request. To download the image:

1. click the green checkmark; you'll go to a page at a URL like `https://gitlab.com/publiclab/image-builder-rpi/pipelines/########/builds`
2. On this page, click the `Jobs` tab, next to `Pipeline`
3. Click the green `Passed` button
4. Click `Download` in the right-hand sidebar
5. Unzip the `artifacts.zip` file, and also the `hypriotos-rpi-camera_web.img.zip` within it
6. Use a program like https://etcher.io/ to flash it to an SD card

You'll also be able to read the output of the image generation in this window.

We hope to create a bot to report back the completed image URL in each pull request. If you can help create such a bot, please contact us at:

https://github.com/publiclab/image-builder-rpi/issues/16

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh, did our rename break the building system, @icarito ? Sorry!!!

**Comment by icarito** [comment]
No the rename didn't break the build. There was a temporary network issue I think. I retried and now it failed because npm isn't installed.

**Comment by jywarren** [comment]
oh, i'd like to do both, this is just an initial example attempt! I
definitely think we should create an image-sequencer version of this too.

**Comment by jywarren** [comment]
Now following https://www.thepolyglotdeveloper.com/2018/03/install-nodejs-raspberry-pi-zero-w-nodesource/

**Comment by jywarren** [comment]
So once we get this running, we should be able to just swap "infragram" with "image-sequencer" in a new PR and then it should work there too. They have similar node/npm dependencies!

**Comment by jywarren** [comment]
Ah, we're now running out of space -- is there a way to expand the image?

```
tar: ./node-v9.7.1-linux-armv6l: Cannot mkdir: No space left on device
tar: ./node-v9.7.1-linux-armv6l/lib/node_modules/npm/lib/install/exists.js: Cannot open: No such file or directory
```

**Comment by icarito** [comment]
Yes! I ran into the same issue while trying to integrate Peggy scripts + Desktop environment.
Please see https://github.com/publiclab/pi-builder/pull/12/files#diff-55f0a4e44112d8684fa3f85db6490f3cL87

This replaces the standard hypriot root base filesystem with a custom built one by us in Jenkins (set to 2GB instead of 1GB images).

**Comment by icarito** [comment]
The repository for the enlarged rootfs is at https://gitlab.com/publiclab/image-builder-raw

**Comment by jywarren** [comment]
OK! Added that to increase the image size. Awesome, thanks!

**Comment by icarito** [comment]
Yes, it is necessary to update the checksum too, forgot to mention it: https://github.com/publiclab/pi-builder/pull/12/files#diff-228984280290be5309df88a7d32cf31dL8

**Comment by jywarren** [comment]
It worked!!!

**Comment by jywarren** [comment]
Er, did it? Oh, it doesn't seem to have triggered.

**Comment by icarito** [comment]
How strange, this should trigger automatically...

**Comment by icarito** [comment]
I found a webhook confused about the old URL, fixing it...

**Comment by jywarren** [comment]
Downloading this now to test!

**Comment by jywarren** [comment]
It worked!!! OK, so now I have to rebase this or combine it with commits from https://github.com/publiclab/pi-builder/pull/13/files, because we actually need that installed to be able to route the video stream into Infragram as per:

https://publiclab.org/questions/warren/12-05-2017/how-can-we-stream-video-to-spectralworkbench-org-or-infragram-org-from-a-raspberry-pi-camera

**Comment by jywarren** [comment]
Looks like you can just load it as an image using this code, and insert it:

```
      var piImage = new Image();

      piImage.onload = function() {
        context.drawImage(piImage, 0, 0, canvas.width, canvas.height);
      }

      piImage.src = "http://pi.local/cam_pic.php?time=" + new Date().getTime();
```

**Comment by jywarren** [comment]
Not sure but we'd integrate with this file:

https://github.com/publiclab/infragram/blob/063acbf333ea45e980ffb56ad5d79cdc6a66391f/src/io/camera.js#L83

needs some experimentation!

**Comment by jywarren** [comment]
OK, I've rebased this over the `camera_web` branch that includes the PiCam web software, and opened a separate PR for it to test. If it works, we could move over there (for a cleaner PR) or close that and merge it back in here, depending on what people want.

**Comment by jywarren** [comment]
Wow, this worked:

screen shot 2018-10-26 at 4 07 59 pm

I'm super excited about this! Although I'm having trouble with the v2 NOIR camera.  

Next - add a button to initiate this script and then do some tidying up in the Infragram repository...

**Comment by jywarren** [comment]
OK! I'm closing in favor of the tidier #40 -- this is working! Infragram may need some tidying but otherwise this is good to go, and can be used as a template for doing the same with `image-sequencer` too!

**Comment by jywarren** [comment]
@maykef i'm interested in learning more about CM 3 -- do you have a link? As to OpenCV, there are 2 approaches. First, this recipe uses OpenCV: https://github.com/publiclab/pi-builder/pull/12

Second, we have a module in planning for image-sequencer that uses the cross-compiled OpenCV.js: https://github.com/publiclab/image-sequencer/issues/237 -- this might be really interesting because it'd be so modular.

**Comment by maykef** [comment]
Hey @jywarren I've been working like crazy on the camera. I think I've done most of the hardest part. The cameras trigger within half millisecond (thanks to using multiprocessing module)
clip_raspicam
.

**Comment by maykef** [comment]
Are we running a Kickstarter campaign for this?

**Comment by jywarren** [comment]
lol should we? :-)

**Comment by maykef** [comment]
@jywarren Hey
I have finished with most of the work for the multispectral pi. What I want to do now is to run image-sequencer from a web browser accessed through an access point on the pi. 
Image-sequencer should show the four images captured by the camera and then do all the processing

**Comment by jywarren** [comment]
Ooh, ok! Remind me, are you using 2 cameras? And what are the commands to
take your images?

Awesome! I have image sequencer running on the pi already, so it's a matter
of connecting it up w the camera scripts. 👍🏽

**Comment by jywarren** [comment]
oh interesting, but can you explain what the 4 images are? I am not quite
following, it's 2 cameras, right? Thank you and sorry for being dense!

**Comment by maykef** [comment]
No worries.
These are the 4 bands. Camera one captures the R, G and B, while camera 2 collects the NIR band(845nm).
screenshot 2018-11-20 at 22 52 08

**Comment by jywarren** [comment]
Oh, of course. Sorry, when i process, i usually have 3 bands in one image, and another in a second, so mentally i think of 2 images. 

So you're accessing it with `picamera.PiCamera(0)` and `picamera.PiCamera(1)` -- we need to figure out how to fetch images from both cameras. I'll open a new issue for this!

**Comment by maykef** [comment]
Apart from fetching the images, we need to think about image registration within Infragram. I've got an OpenCV script that already does the job, but the CM seems to run out of memory while doing the registration.

**Pull request closed without merging**
