### PR TITLE
Witty test pr

### PR DESCRIPTION
**Pull request by icarito**
:crossed_fingers:  :building_construction: 

Thanks for opening a pull request! In this repository, opening a PR will initiate the generation of a new Raspberry Pi image, and create an image file you can download and use in your Raspberry Pi.

The changes you add to the pull request, such as adding software to install, will be run on the generated image.

For an example, see the software installed and configured in this pull request: https://github.com/publiclab/image-builder-rpi/pull/15/files

### Recipe

Use this space to describe what your "recipe" is intended to install and configure on a Raspberry Pi:

****

### Download instructions

Generating the image will take a few minutes. Once the image is prepared, and if it succeeded, you'll see a green checkmark at the bottom of the pull request. To download the image:

1. click the green checkmark; you'll go to a page at a URL like `https://gitlab.com/publiclab/image-builder-rpi/pipelines/########/builds`
2. On this page, click the `Jobs` tab, next to `Pipeline`
3. Click the green `Passed` button
4. Click `Download` in the right-hand sidebar
5. Unzip the `artifacts.zip` file, and also the `hypriotos-rpi-camera_web.img.zip` within it
6. Use a program like https://etcher.io/ to flash it to an SD card

You'll also be able to read the output of the image generation in this window.

We hope to create a bot to report back the completed image URL in each pull request. If you can help create such a bot, please contact us at:

https://github.com/publiclab/image-builder-rpi/issues/16

Thanks!

### CODE REVIEW

**Comment by icarito** [comment]
While I'm still unable to get Gitlab CI to report back here, this did create an image!
https://gitlab.com/publiclab/pi-builder-ci/-/jobs/121781276 @imvectech  this is a replica of #59 that I made to test why our CI system isn't working correctly.

I guess I'll remove all integration and the Gitlab repositories and just start over from scratch.

**Comment by icarito** [comment]
This is the relevant build output:
```
+ wget http://www.uugear.com/repo/WittyPi2/installWittyPi.sh
--2018-11-17 03:58:02--  http://www.uugear.com/repo/WittyPi2/installWittyPi.sh
Resolving www.uugear.com (www.uugear.com)... 172.104.156.161
Connecting to www.uugear.com (www.uugear.com)|172.104.156.161|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5063 (4.9K) [text/x-sh]
Saving to: 'installWittyPi.sh'

     0K ....                                                  100% 38.0M=0s

2018-11-17 03:58:03 (38.0 MB/s) - 'installWittyPi.sh' saved [5063/5063]

+ sh installWittyPi.sh
+ yes
================================================================================
|                                                                              |
|                   Witty Pi Software Installation Script                      |
|                                                                              |
================================================================================
>>> Enable I2C
Seems i2c1 parameter already set, skip this step.
File raspi-blacklist.conf does not exist, skip this step.
>>> Install i2c-tools
Seems i2c-tools is installed already, skip this step.
>>> Install wiringPi
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package wiringpi
```

**Comment by imvectech** [comment]
Yep! deffinitely apt cleanup must go underneath ;)

**Comment by imvectech** [comment]
Still don't really know how pull requests and commits work... https://github.com/imvectech/pi-builder/pull/1

**Pull request closed without merging**
